import { Analytics } from "@vercel/analytics/next"
import type { Metadata } from "next";
import "./globals.css";
import Footer from "@/_Components/Footer";
import Header from "@/_Components/Header";



export const metadata: Metadata = {
  title: "G.S.A.S",
  description: "Generated by create next app",
  icons: "/logoModifier.png"
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fr">
      <body
      >
        <Header />
        <main>
          {children}
          <Analytics/>
        </main>
        <Footer />
      </body>
    </html>
  );
}
